replay_buffer:
  _target_: buffers.replay_buffer_latent_model.ReplayBuffer
  buffer_size: ${replay_buffer_size}
  batch_size: ${batch_size}
  nstep: ${nstep}
  discount: ${discount}
  frame_stack: ${frame_stack}
