agent:
  _target_: agents.ddpg.DDPG_Agent
  obs_dim: ??? # to be specified later
  action_dim: ??? # to be specified later
  action_range: ??? # to be specified later
  device: ${device}
  hidden_dim: 1024
  hidden_depth: 2
  discount: 0.99
  actor_lr: 1e-4
  actor_betas: [0.9, 0.999]
  actor_update_frequency: 1
  critic_lr: 1e-4
  critic_betas: [0.9, 0.999]
  critic_tau: 0.005
  critic_target_update_frequency: 2
  batch_size: 1024
  num_expl_steps: 0
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
