
agent_name: lail

agent:
  _target_: agents.lail.LailAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  reward_d_coef: 2.0
  discriminator_lr: ${discriminator_lr}
  spectral_norm_bool: ${spectral_norm_bool}
  GAN_loss: ${GAN_loss}
  from_dem: ${from_dem}

