
agent_name: patchAIL

agent:
  _target_: agents.patchAIL.PatchAilAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: 1e-4
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  reward_type: ${reward_type}
  reward_scale: ${reward_scale}
  disc_lr: ${discriminator_lr}
  use_simreg: True
  sim_rate: 'auto-1.3'
  # sim_rate: 2.0
