replay_buffer_expert:
  _target_: buffers.np_replay_buffer_obs_only.EfficientReplayBuffer
  buffer_size: ${replay_buffer_capacity}
  batch_size: ${batch_size}
  nstep: ${nstep}
  discount: ${discount}
  frame_stack: ${frame_stack}
