defaults:
  - _self_
  - replay_buffer@_global_: latent_model
  - replay_buffer_expert@_global_: latent_model_expert
  - task@_global_: walker_walk
  - agent@_global_: lail
  - expert@_global_: ddpg
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 1
action_repeat: 1
discount: 0.99
image_height: 64
image_width: 64
# train settings
num_seed_frames: 4000
num_seed_frames_update_latent_only: 10000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 1000000
sequence_length: 10
batch_size_actor: 256
batch_size_latent: 32
# misc
seed: 1
device: cuda
save_video: false
save_train_video: false
use_tb: false
# experiment
experiment: exp
# agent
lr_actor: 1e-4
lr_latent: 1e-4
feature_dim_agent: 256
z1_dim: 32
z2_dim: 256
hidden_units: [256, 256]
tau: 5e-3
# expert data
num_expert_episodes: 100
frame_skip: 1
#discriminator
lr_discriminator: 3e-4
GAN_loss: least-square
from_dem: false
  
hydra:
  run:
    dir: ./experiments/exp_lail/${now:%Y.%m.%d}/${now:%H%M}_${hydra.job.override_dirname}
  sweep:
    dir: ./experiments/exp_multirun_lail_${task_name}_num_expert_episodes_${num_expert_episodes}/GAN_loss_${GAN_loss}_from_dem_${from_dem}/
    subdir: ${now:%Y.%m.%d}_${now:%H%M}_${hydra.job.override_dirname}
  launcher:
    timeout_min: 18000000
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./experiments/exp_multirun_lail_${task_name}_num_expert_episodes_${num_expert_episodes}/GAN_loss_${GAN_loss}_from_dem_${from_dem}/${now:%Y.%m.%d}_${now:%H%M}
